version: '3'
services:
  wishlist:
    build: .
    ports:
      - "3000:3000"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 200M